CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    employee_no VARCHAR(64),
    email VARCHAR(128),
    phone VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    department_id BIGINT,
    position_id BIGINT,
    direct_manager_id BIGINT,
    last_login_at TIMESTAMPTZ,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_user_username_active
    ON sys_user (username)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    builtin BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_role_code_active
    ON sys_role (code)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS sys_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(32) NOT NULL,
    parent_id BIGINT,
    path VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_permission_code_active
    ON sys_permission (code)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_sys_user_role_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_sys_user_role_role FOREIGN KEY (role_id) REFERENCES sys_role (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_user_role_active
    ON sys_user_role (user_id, role_id)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS sys_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_sys_role_permission_role FOREIGN KEY (role_id) REFERENCES sys_role (id),
    CONSTRAINT fk_sys_role_permission_permission FOREIGN KEY (permission_id) REFERENCES sys_permission (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_role_permission_active
    ON sys_role_permission (role_id, permission_id)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS org_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    leader_user_id BIGINT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_org_department_parent FOREIGN KEY (parent_id) REFERENCES org_department (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_org_department_code_active
    ON org_department (code)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS org_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_org_position_department FOREIGN KEY (department_id) REFERENCES org_department (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_org_position_code_active
    ON org_position (code)
    WHERE deleted = FALSE;

ALTER TABLE sys_user
    ADD CONSTRAINT fk_sys_user_department FOREIGN KEY (department_id) REFERENCES org_department (id);

ALTER TABLE sys_user
    ADD CONSTRAINT fk_sys_user_position FOREIGN KEY (position_id) REFERENCES org_position (id);

ALTER TABLE sys_user
    ADD CONSTRAINT fk_sys_user_direct_manager FOREIGN KEY (direct_manager_id) REFERENCES sys_user (id);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64),
    actor_user_id BIGINT,
    actor_username VARCHAR(64),
    action VARCHAR(128) NOT NULL,
    target_type VARCHAR(64),
    target_id BIGINT,
    result VARCHAR(32) NOT NULL,
    detail JSONB,
    client_ip VARCHAR(64),
    user_agent VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT
);

CREATE INDEX IF NOT EXISTS ix_audit_log_actor_created_at
    ON audit_log (actor_user_id, created_at);

CREATE INDEX IF NOT EXISTS ix_audit_log_target
    ON audit_log (target_type, target_id);
