CREATE TABLE IF NOT EXISTS approval_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR(64) NOT NULL,
    title VARCHAR(200) NOT NULL,
    type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    applicant_id BIGINT NOT NULL,
    applicant_name VARCHAR(100) NOT NULL,
    department_id BIGINT,
    department_name VARCHAR(100),
    urgent BOOLEAN NOT NULL DEFAULT FALSE,
    amount NUMERIC(14, 2),
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    form_data TEXT NOT NULL,
    submitted_at TIMESTAMPTZ,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT ux_approval_request_no UNIQUE (request_no),
    CONSTRAINT fk_approval_request_applicant FOREIGN KEY (applicant_id) REFERENCES sys_user (id),
    CONSTRAINT fk_approval_request_department FOREIGN KEY (department_id) REFERENCES org_department (id)
);

CREATE INDEX IF NOT EXISTS ix_approval_request_applicant
    ON approval_request (applicant_id, created_at);

CREATE INDEX IF NOT EXISTS ix_approval_request_status_type
    ON approval_request (status, type);

CREATE TABLE IF NOT EXISTS approval_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    content_type VARCHAR(128),
    file_size BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_approval_attachment_request FOREIGN KEY (request_id) REFERENCES approval_request (id)
);

CREATE INDEX IF NOT EXISTS ix_approval_attachment_request
    ON approval_attachment (request_id);

CREATE TABLE IF NOT EXISTS approval_action_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    actor_name VARCHAR(100) NOT NULL,
    action VARCHAR(64) NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32),
    comment VARCHAR(1000),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_approval_action_log_request FOREIGN KEY (request_id) REFERENCES approval_request (id),
    CONSTRAINT fk_approval_action_log_actor FOREIGN KEY (actor_id) REFERENCES sys_user (id)
);

CREATE INDEX IF NOT EXISTS ix_approval_action_log_request
    ON approval_action_log (request_id, created_at);
