CREATE TABLE IF NOT EXISTS approval_workflow_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_approval_workflow_instance_request FOREIGN KEY (request_id) REFERENCES approval_request (id)
);

CREATE INDEX IF NOT EXISTS ix_approval_workflow_instance_request
    ON approval_workflow_instance (request_id);

CREATE TABLE IF NOT EXISTS approval_workflow_node_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_instance_id BIGINT NOT NULL,
    request_id BIGINT NOT NULL,
    node_name VARCHAR(100) NOT NULL,
    approver_rule VARCHAR(64) NOT NULL,
    approver_id BIGINT NOT NULL,
    approver_name VARCHAR(100) NOT NULL,
    status VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_approval_workflow_node_instance_workflow FOREIGN KEY (workflow_instance_id) REFERENCES approval_workflow_instance (id),
    CONSTRAINT fk_approval_workflow_node_instance_request FOREIGN KEY (request_id) REFERENCES approval_request (id),
    CONSTRAINT fk_approval_workflow_node_instance_approver FOREIGN KEY (approver_id) REFERENCES sys_user (id)
);

CREATE INDEX IF NOT EXISTS ix_approval_workflow_node_instance_workflow
    ON approval_workflow_node_instance (workflow_instance_id, sort_order);

CREATE INDEX IF NOT EXISTS ix_approval_workflow_node_instance_request
    ON approval_workflow_node_instance (request_id);

CREATE TABLE IF NOT EXISTS approval_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    workflow_instance_id BIGINT NOT NULL,
    node_instance_id BIGINT NOT NULL,
    assignee_id BIGINT NOT NULL,
    assignee_name VARCHAR(100) NOT NULL,
    status VARCHAR(32) NOT NULL,
    comment VARCHAR(1000),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acted_at TIMESTAMPTZ,
    due_at TIMESTAMPTZ,
    overdue BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_approval_task_request FOREIGN KEY (request_id) REFERENCES approval_request (id),
    CONSTRAINT fk_approval_task_workflow FOREIGN KEY (workflow_instance_id) REFERENCES approval_workflow_instance (id),
    CONSTRAINT fk_approval_task_node FOREIGN KEY (node_instance_id) REFERENCES approval_workflow_node_instance (id),
    CONSTRAINT fk_approval_task_assignee FOREIGN KEY (assignee_id) REFERENCES sys_user (id)
);

CREATE INDEX IF NOT EXISTS ix_approval_task_assignee_status
    ON approval_task (assignee_id, status, assigned_at);

CREATE INDEX IF NOT EXISTS ix_approval_task_request
    ON approval_task (request_id, status);
